# Intro to Pytorch Tensors

#### Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing.

In [1]:
import torch
import numpy as np

## Initialize Tensors

### There are multiple ways of initlizing Tensors
- Directly from the data
- from Numpy array
- from Another Tensor
- using inbuilt methods

In [2]:
# Directly from the data
data = [[1,2,3], [4,5,6]]
tensor_data = torch.tensor(data)

print(data)
print(tensor_data)

[[1, 2, 3], [4, 5, 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
# from a Numpy array
np_data = np.array(data)
print(np_data)

tensor_data = torch.from_numpy(np_data)
print(tensor_data)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [8]:
# from another Tensor

tensor_ones = torch.ones_like(tensor_data)
print(tensor_ones)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [10]:
# with inbuilt methods
shape = (2, 3)

t_z = torch.zeros(shape)
print(t_z)

t_r = torch.rand(shape)
print(t_r)

t_o = torch.ones(shape)
print(t_o)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.7790, 0.9629, 0.1711],
        [0.9186, 0.9896, 0.6632]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


### Tensor Attributes

In [11]:
print("shape  : ", tensor_data.shape)
print("dtype  : ", tensor_data.dtype)
print("device : ", tensor_data.device)

shape  :  torch.Size([2, 3])
dtype  :  torch.int32
device :  cpu


In [12]:
torch.cuda.is_available()

True

## Tensor Operations

### basic operations

In [14]:
#Allocate memory for tensor_data on cuda
print(tensor_data.device)
tensor_data = tensor_data.to('cuda')
print(tensor_data.device)


cuda:0
cuda:0


In [15]:
tensor = torch.ones(4,4)

# indexing and slicing
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [16]:
# concatenate
torch.cat([tensor, tensor, tensor], dim=1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [17]:
# concatenate
torch.cat([tensor, tensor, tensor], dim=0)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [19]:
#element-wise product

#using mul
print(tensor.mul(tensor))

# using *
print(tensor * tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [20]:
# matrix multiplication

#using mul
print(tensor.matmul(tensor))

# using *
print(tensor @ tensor)

tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])
tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])


### Inplace operations

inplace operations will have a a default suffix of '_'

In [22]:
print(tensor)
tensor.add_(6)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[7., 6., 7., 7.],
        [7., 6., 7., 7.],
        [7., 6., 7., 7.],
        [7., 6., 7., 7.]])


In [25]:
print(tensor)
tensor.amin(dim=1)


tensor([[7., 6., 7., 7.],
        [7., 6., 7., 7.],
        [7., 6., 7., 7.],
        [7., 6., 7., 7.]])


tensor([6., 6., 6., 6.])

In [27]:
print(tensor)
tensor.amin(dim=1, keepdim=True)

tensor([[7., 6., 7., 7.],
        [7., 6., 7., 7.],
        [7., 6., 7., 7.],
        [7., 6., 7., 7.]])


tensor([[6.],
        [6.],
        [6.],
        [6.]])

In [26]:
print(tensor)
tensor.amin(dim=0)

tensor([[7., 6., 7., 7.],
        [7., 6., 7., 7.],
        [7., 6., 7., 7.],
        [7., 6., 7., 7.]])


tensor([7., 6., 7., 7.])